#!/bin/bash

prefix=/usr/local

rm -rfv ${prefix}/include/colib
rm -rfv ${prefix}/include/iulib
rm -rfv ${prefix}/include/ocropus
rm -rfv ${prefix}/include/ocrorast
rm -rfv ${prefix}/include/ocrolseg
rm -rfv ${prefix}/include/ocrofst
rm -rfv ${prefix}/lib/libiulib*
rm -rfv ${prefix}/lib/libocropus*
rm -rfv ${prefix}/lib/libocrorast*
rm -rfv ${prefix}/lib/libocrofst*
rm -rfv ${prefix}/lib/python*/dist-packages/_ocro*.so
rm -rfv ${prefix}/lib/python*/dist-packages/ocro*
